tap "nikitabobko/tap"
tap "felixkratz/formulae"

cask "ghostty"
cask "obsidian"
cask "nikitabobko/tap/aerospace"
cask "vorssaint"
cask "raycast"
cask "leader-key"

brew "felixkratz/formulae/borders"
brew "fzf"
brew "zoxide"
brew "eza"
brew "git"
