#!/bin/bash

# JankyBorders — highlight the focused AeroSpace window
# https://github.com/FelixKratz/JankyBorders

options=(
	style=round
	width=3.0
	hidpi=on
	order=above
	active_color=0x800a84ff
	inactive_color=0x33494d64
)

borders "${options[@]}"
